// Copies contract ABIs from the Foundry build into typed TypeScript modules, so the web
// app can never drift from the deployed contracts. Run after `forge build`:
//   pnpm sync-abi
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const foundryOut = join(root, "..", "contracts", "out");
const target = join(root, "lib", "abi");

const contracts = [
  { name: "Launchpad", exportName: "launchpadAbi" },
  { name: "HookKernel", exportName: "hookKernelAbi" },
  { name: "BlockCatalog", exportName: "blockCatalogAbi" },
  { name: "LaunchRouter", exportName: "launchRouterAbi" },
  { name: "LiquidityManager", exportName: "liquidityManagerAbi" },
  { name: "BaseBlock", exportName: "ruleBlockAbi" },
];

mkdirSync(target, { recursive: true });
for (const { name, exportName } of contracts) {
  const artifact = JSON.parse(readFileSync(join(foundryOut, `${name}.sol`, `${name}.json`), "utf8"));
  const body = `// Generated by scripts/sync-abi.mjs from contracts/out/${name}.sol. Do not edit.\n` +
    `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(target, `${name}.ts`), body);
  console.log(`wrote lib/abi/${name}.ts (${artifact.abi.length} entries)`);
}
