// Generated by scripts/sync-abi.mjs from contracts/out/BaseBlock.sol. Do not edit.
export const ruleBlockAbi = [
  {
    "type": "function",
    "name": "afterSwap",
    "inputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct SwapContext",
        "components": [
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "PoolId"
          },
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactInput",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "impactPpm",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "subjectAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "openedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "timestamp",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "subjectSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "isLaunch",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "state",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "beforeAddLiquidity",
    "inputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct LiquidityContext",
        "components": [
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "PoolId"
          },
          {
            "name": "openedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "timestamp",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "isLaunch",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "fromLaunchpad",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "beforeSwap",
    "inputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct SwapContext",
        "components": [
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "PoolId"
          },
          {
            "name": "isBuy",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "exactInput",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "impactPpm",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "subjectAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "openedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "timestamp",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "subjectSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "isLaunch",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "state",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint24",
        "internalType": "uint24"
      },
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hookPoints",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "validateConfig",
    "inputs": [
      {
        "name": "config",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "isLaunch",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  }
] as const;
